# Generated by Django 4.2.16 on 2024-11-09 19:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntifraudDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('object_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culqi_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('interval_unit_time', models.CharField(max_length=50)),
                ('interval_count', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culqi_id', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('object_type', models.CharField(max_length=20)),
                ('antifraud_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.antifrauddetails')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Ingrese una placa válida.')], verbose_name='Placa del Carro')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Carro')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color del Carro')),
                ('modelo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Modelo del Carro')),
                ('dia_llegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Día de Llegada')),
                ('dia_salida', models.DateTimeField(blank=True, null=True, verbose_name='Día de Salida')),
                ('numero_telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de teléfono no válido.')], verbose_name='Número de Teléfono')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('espera', 'En Espera'), ('proceso', 'En Proceso'), ('terminado', 'Terminado')], default='espera', max_length=10, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='services.empresa')),
            ],
        ),
    ]
