# Generated by Django 4.2.16 on 2024-12-09 20:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culqi_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^\\d±!@£$%^&*_+§¡€#¢§¶•ªº«\\<>-?:;|=.,]{2,50}$', 'Nombre no válido.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^\\d±!@£$%^&*_+§¡€#¢§¶•ªº«\\<>-?:;|=.,]{2,50}$', 'Apellido no válido.')])),
                ('address', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de teléfono no válido.')])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
