# Generated by Django 4.2.16 on 2024-12-12 18:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_customer_address_alter_customer_address_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntifraudDetails',
        ),
        migrations.AlterField(
            model_name='carro',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='dia_llegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carro',
            name='dia_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='estado',
            field=models.CharField(choices=[('espera', 'En Espera'), ('proceso', 'En Proceso'), ('terminado', 'Terminado')], default='espera', max_length=10),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='numero_telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de teléfono no válido.')]),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Ingrese una placa válida.')]),
        ),
        migrations.AlterField(
            model_name='carro',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
