# Generated by Django 4.2.16 on 2025-07-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC'),
        ),
    ]
